### ISSUE TITLE
Tracking issue for the datastructure of logic

### ISSUE THREAD

**Issue by default-username-852** [inda19plusplus/logik#13]
Tracking issue for the logic's datastructure. It specifies what should be part of the datastructure of the logic. Feel free to comment if you feel anything is missing.

**Features**

- [ ] The concept of subnets

- [ ] The state that the subnets are in

- [ ] The concept of components

- [ ] What type of component that each component is

- [ ] How the components and subnets are linked

- [ ] Create tests

- [ ] Document the code
