### ISSUE TITLE
Tracking issue for interop between the GUI and the logic

### ISSUE THREAD

**Issue by default-username-852** [inda19plusplus/logik#15]
This is the tracking issue for interop between the GUI and the logic. It should broadly specify what methods Rust should expose to be able to be properly interacted with. Feel free to discuss what other functionality rust should expose.

**Features**

- [ ] Querying the state of subnets given a subnet ID.

- [ ] Ablility for the caller to add subnets and assign them an ID.

- [ ] Ability for the caller to remove a subnet with a given ID.

- [ ] Ability for the caller to link or unlink components with subnets. The caller should also be able to specify which port to link or unlink. How the port indicies are determined is not yet decided.

- [ ] Ability to add new components. When adding components, Rust should tell the caller what id the added component has.

- [ ] Ability to remove components given the component ID.

- [ ] A way to advance the simulation
